/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Action to perform on the system.
 */
export type Action3 = 'PUBLISH' | 'UNPUBLISH' | 'SETDEFAULT' | 'UNSETDEFAULT' | 'SETGLOBALDEFAULT' | 'UNSETGLOBALDEFAULT' | 'CLONE';

export const Action3 = {
    Publish: 'PUBLISH' as Action3,
    Unpublish: 'UNPUBLISH' as Action3,
    Setdefault: 'SETDEFAULT' as Action3,
    Unsetdefault: 'UNSETDEFAULT' as Action3,
    Setglobaldefault: 'SETGLOBALDEFAULT' as Action3,
    Unsetglobaldefault: 'UNSETGLOBALDEFAULT' as Action3,
    Clone: 'CLONE' as Action3
};

