/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationSummary { 
    /**
     * The name of the application. The name does not have to be unique, but the combination of name and version does.
     */
    name?: string;
    /**
     * The date this application was last modified in ISO 8601 format.
     */
    lastModified?: string;
    /**
     * Whether the application is public or private.
     */
    isPublic?: boolean;
    /**
     * The system id of the execution system where this app should run.
     */
    executionSystem?: string;
    /**
     * The version of the application in #.#.# format. While the version does not need to be unique, the combination of name and version does have to be unique.
     */
    version?: string;
    /**
     * The short description of this application.
     */
    shortDescription?: string;
    /**
     * Unique id of this app. Comprised of the app name-version.
     */
    id?: string;
    /**
     * The number of times this application has been revised.
     */
    revision?: number;
}

