/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationParameterDetails { 
    /**
     * The command line value of this parameter (ex -n, --name, -name, etc)
     */
    argument?: string;
    /**
     * Whether the argument value should be passed into the wrapper at run time
     */
    showArgument?: boolean;
    /**
     * Description of this parameter.
     */
    description?: string;
    /**
     * The label for this parameter
     */
    label?: string;
}

