/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationInputDetails } from './applicationInputDetails';
import { ApplicationInputValue } from './applicationInputValue';
import { ApplicationInputOntology } from './applicationInputOntology';


export interface ApplicationInput { 
    value?: ApplicationInputValue;
    details?: ApplicationInputDetails;
    semantics?: ApplicationInputOntology;
    /**
     * The id of this input. This will be the replacement string in your wrapper scripts.
     */
    id?: string;
}

