/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationInputValue { 
    /**
     * Should this parameter be visible? If not, there must be a default and it will be required.
     */
    visible?: boolean;
    /**
     * The default value for this parameter. The type will be determined by the value.type field.
     */
    defaultValue?: string;
    /**
     * Is this parameter required? If visible is false, this must be true.
     */
    required?: boolean;
    /**
     * The order in which this parameter should be printed when generating an execution command for forked execution. This will also be the order in which paramters are returned in the response json.
     */
    order?: number;
    /**
     * The regular expression used to validate this parameter value. For enumerations, separate values with |
     */
    validator?: string;
}

