/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Tier } from './tier';


export interface ClientRequest { 
    tier?: Tier;
    /**
     * Callback URL for OAuth authentication grant.
     */
    callbackUrl?: string;
    /**
     * The name of the client.
     */
    name?: string;
    /**
     * Description of the client. This will be shown to users when authentication via OAuth web flows
     */
    description?: string;
}
export namespace ClientRequest {
}


