/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Client { 
    /**
     * The name of the client.
     */
    name?: string;
    /**
     * The API key for this client.
     */
    consumerKey?: string;
    /**
     * The access tier for this client.
     */
    tier?: string;
    /**
     * Callback URL for OAuth authentication grant.
     */
    callbackUrl?: string;
    /**
     * The API secret for this client.
     */
    consumerSecret?: string;
    /**
     * Description of the client. This will be shown to users when authentication via OAuth web flows
     */
    description?: string;
}

