/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The execution paradigm used to run jobs on this system.
 */
export type ExecutionType2 = 'HPC' | 'CONDOR' | 'CLI';

export const ExecutionType2 = {
    Hpc: 'HPC' as ExecutionType2,
    Condor: 'CONDOR' as ExecutionType2,
    Cli: 'CLI' as ExecutionType2
};

