/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Action1 } from './action1';


export interface FileOperationRequest { 
    action?: Action1;
    /**
     * New name of the file or folder. Only used with the rename action.
     */
    newName?: string;
    /**
     * Name of new directory. Only used with the mkdir action.
     */
    dirName?: string;
    /**
     * Destination to which to move the file or folder. Only used with the move action.
     */
    newPath?: string;
    /**
     * Destination to which to copy the file or folder. Only used with the copy action.
     */
    destPath?: string;
}
export namespace FileOperationRequest {
}


