/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobInputs } from './jobInputs';
import { JobParameters } from './jobParameters';
import { Notification } from './notification';


export interface JobRequest { 
    inputs?: JobInputs;
    /**
     * The name of the job.
     */
    name?: string;
    parameters?: JobParameters;
    /**
     * The queue to which this job should be submitted. This is optional and only applies when the execution system has a batch scheduler.
     */
    batchQueue?: string;
    /**
     * The unique id of the storage system on which this job\'s output will be staged.
     */
    archiveSystem?: string;
    /**
     * The number of processors this application should utilize while running. If the application is not of executionType PARALLEL, this should be 1.
     */
    processorsPerNode?: number;
    /**
     * The requested memory for this application to run given in GB.
     */
    memoryPerNode?: string;
    /**
     * The path of the archive folder for this job on the user\'s default storage sytem.
     */
    archivePath?: string;
    /**
     * An array of notifications you wish to receive.
     */
    notifications?: Array<Notification>;
    /**
     * The unique name of the application being run by this job. This must be a valid application that the calling user has permission to run.
     */
    appId?: string;
    /**
     * The number of processors this application should utilize while running. If the application is not of executionType PARALLEL, this should be 1.
     */
    nodeCount?: number;
    /**
     * Whether the output from this job should be archived. If true, all new files created by this application\'s execution will be archived to the archivePath in the user\'s default storage system.
     */
    archive?: boolean;
    /**
     * The requested compute time needed for this application to complete given in HH:mm:ss format.
     */
    maxRunTime?: string;
}

