/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JobSummary { 
    /**
     * The status of the job. Possible values are: PENDING, STAGING_INPUTS, CLEANING_UP, ARCHIVING, STAGING_JOB, FINISHED, KILLED, FAILED, STOPPED, RUNNING, PAUSED, QUEUED, SUBMITTING, STAGED, PROCESSING_INPUTS, ARCHIVING_FINISHED, ARCHIVING_FAILED
     */
    status?: string;
    /**
     * The name of the job.
     */
    name?: string;
    /**
     * The system id of the execution system.
     */
    executionSystem?: string;
    /**
     * The date the job started in ISO 8601 format.
     */
    startTime?: string;
    /**
     * The unique name of the application being run by this job. This must be a valid application that the calling user has permission to run.
     */
    appId?: string;
    /**
     * The job owner.
     */
    owner?: string;
    /**
     * The date the job ended in ISO 8601 format.
     */
    endTime?: string;
    /**
     * The unique id of the job.
     */
    id?: string;
}

