/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { JobInputs } from './jobInputs';
import { JobParameters } from './jobParameters';
import { Notification } from './notification';


export interface JobSubmission { 
    inputs?: JobInputs;
    /**
     * The name of the job.
     */
    name?: string;
    parameters?: JobParameters;
    /**
     * The queue to which this job should be submitted. This is optional and only applies when the execution system has a batch scheduler.
     */
    batchQueue?: string;
    /**
     * The system on which the job data will be archived
     */
    archiveSystem?: string;
    /**
     * The number of processors this application should utilize while running.
     */
    processorsPerNode?: number;
    /**
     * The maximum amount of memory needed for this application to run given in GB.
     */
    maxMemory?: string;
    /**
     * The path of the archive folder for this job on the archiveSystem. Defaults to the user\'s default storage system.
     */
    archivePath?: string;
    /**
     * An array of notifications you wish to receive.
     */
    notifications?: Array<Notification>;
    /**
     * The unique name of the application being run by this job. This must be a valid application that the calling user has permission to run.
     */
    appId?: string;
    /**
     * The number of nodes this application should utilize while running. If the application is not of executionType PARALLEL, this should be 1.
     */
    nodeCount?: number;
    /**
     * Whether the output from this job should be archived. If true, all new files created by this application\'s execution will be archived to the archivePath in the user\'s default storage system.
     */
    archive?: boolean;
    /**
     * The estimated compute time needed for this application to complete given in hh:mm:ss format.
     */
    maxRunTime?: string;
}

