/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserCredential } from './userCredential';
import { Protocol2 } from './protocol2';


export interface LoginConfig { 
    /**
     * The hostname or ip address of the submission server
     */
    host?: string;
    protocol?: Protocol2;
    /**
     * The port number of the submission server.
     */
    port?: number;
    auth?: UserCredential;
}
export namespace LoginConfig {
}


