/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MetadataRequest { 
    /**
     * The UUID of the schema that should be used to validate this request.
     */
    schemaId?: string;
    /**
     * The name of this metadata
     */
    name?: string;
    /**
     * A free text or JSON string containing the metadata stored for the given associationIds
     */
    value?: string;
    /**
     * UUIDs of associated Agave entities, including the Data to which this Metadata belongs.
     */
    associationIds?: Array<string>;
}

