/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Metadata { 
    /**
     * The name of this metadata
     */
    name?: string;
    /**
     * A timestamp indicating when this Metadata was created in the metadata store.
     */
    created?: string;
    /**
     * The UUID for this Metadata.
     */
    uuid?: string;
    /**
     * A timestamp indicating when this Metadata was last updated in the metadata store.
     */
    lastUpdated?: string;
    /**
     * UUIDs of associated Agave entities, including the Data to which this Metadata belongs.
     */
    associationIds?: Array<string>;
    /**
     * A free text or JSON string containing the metadata stored for the given associationIds
     */
    value?: string;
    /**
     * The API user who owns this Metadata.
     */
    owner?: string;
    /**
     * The name of the Internal User, if any, who owns this metadata.
     */
    internalUsername?: string;
}

