/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MonitorRequest { 
    /**
     * Whether this monitor is currently active.
     */
    active?: boolean;
    /**
     * The interval in minutes on which this monitor will run. Minimum is 5. Default is 720.
     */
    frequency?: number;
    /**
     * Whether this Monitor should update the system status when the results change. You must have the ADMIN role on the target system to use this feature.
     */
    updateSystemStatus?: boolean;
    /**
     * The id of the sytem to be monitored. This must be an active system registered with the Systems service.
     */
    target?: string;
    /**
     * Internal user account used to perform the check.
     */
    internalUsername?: string;
}

