/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The permission to set
 */
export type Permission4 = 'READ' | 'WRITE' | 'READ_WRITE' | 'ALL' | 'NONE';

export const Permission4 = {
    Read: 'READ' as Permission4,
    Write: 'WRITE' as Permission4,
    ReadWrite: 'READ_WRITE' as Permission4,
    All: 'ALL' as Permission4,
    None: 'NONE' as Permission4
};

