/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostIt { 
    /**
     * The expiration date in ISO 8601 format.
     */
    expires?: string;
    /**
     * The api user who made the PostIt creation request.
     */
    creator?: string;
    /**
     * The url that will be invoked when the PostIt is redeemed.
     */
    url?: string;
    /**
     * The number of invocations remaining on this token.
     */
    remainingUses?: number;
    /**
     * The PostIt nonce.
     */
    postit?: string;
    /**
     * The creation date in ISO 8601 format.
     */
    created?: string;
    /**
     * The url that will be invoked when the PostIt is redeemed.
     */
    method?: string;
    /**
     * The username of the internal user attached to this PostIt.
     */
    internalUsername?: string;
}

