/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Method } from './method';


export interface PostItRequest { 
    /**
     * The url that will be invoked when the PostIt is redeemed.
     */
    url?: string;
    /**
     * The maximum number of invocations remaining on this PostIt. Defaults to no limit
     */
    maxUses?: number;
    /**
     * If true, the provided url will be called without authentication. Default is false
     */
    noauth?: boolean;
    /**
     * The maximum lifetime in seconds of this PostIt on this token. Defaults to 2592000 (30 days)
     */
    lifetime?: number;
    method?: Method;
    /**
     * The username of the internal user attached to this PostIt.
     */
    internalUsername?: string;
}
export namespace PostItRequest {
}


