/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The protocol used to authenticate to the storage server.
 */
export type Protocol1 = 'GRIDFTP' | 'FTP' | 'SFTP' | 'IRODS' | 'LOCAL';

export const Protocol1 = {
    Gridftp: 'GRIDFTP' as Protocol1,
    Ftp: 'FTP' as Protocol1,
    Sftp: 'SFTP' as Protocol1,
    Irods: 'IRODS' as Protocol1,
    Local: 'LOCAL' as Protocol1
};

