/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RemoteFile { 
    /**
     * The mime type of the file/folder. If unknown, it defaults to application/binary.
     */
    mimeType?: string;
    /**
     * The name of the file/folder.
     */
    name?: string;
    /**
     * The file type of the file.
     */
    format?: string;
    /**
     * The date this file was last modified in ISO 8601 format.
     */
    lastModified?: string;
    /**
     * The systemId of the system where this file lives.
     */
    system?: string;
    /**
     * The length of the file/folder.
     */
    length?: number;
    /**
     * The absolute path to the file/folder.
     */
    path?: string;
    /**
     * Whether it is a file or folder.
     */
    type?: string;
    /**
     * The system permission of the invoking user on the file/folder.
     */
    permissions?: string;
}

