/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The role granted this user.
 */
export type Role = 'USER' | 'PUBLISHER' | 'ADMIN' | 'OWNER';

export const Role = {
    User: 'USER' as Role,
    Publisher: 'PUBLISHER' as Role,
    Admin: 'ADMIN' as Role,
    Owner: 'OWNER' as Role
};

