/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of scheduled used to run jobs.
 */
export type Scheduler = 'COBALT' | 'CONDOR' | 'FORK' | 'LOADLEVELER' | 'LSF' | 'MOAB' | 'PBS' | 'SGE' | 'SLURM' | 'TORQUE' | 'UNKNOWN';

export const Scheduler = {
    Cobalt: 'COBALT' as Scheduler,
    Condor: 'CONDOR' as Scheduler,
    Fork: 'FORK' as Scheduler,
    Loadleveler: 'LOADLEVELER' as Scheduler,
    Lsf: 'LSF' as Scheduler,
    Moab: 'MOAB' as Scheduler,
    Pbs: 'PBS' as Scheduler,
    Sge: 'SGE' as Scheduler,
    Slurm: 'SLURM' as Scheduler,
    Torque: 'TORQUE' as Scheduler,
    Unknown: 'UNKNOWN' as Scheduler
};

