/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { BatchQueue } from './batchQueue';
import { StorageConfig } from './storageConfig';
import { Scheduler } from './scheduler';
import { LoginConfig } from './loginConfig';
import { ExecutionType2 } from './executionType2';
import { System } from './system';


export interface StorageSystem extends System { 
}
export namespace StorageSystem {
}


