/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Protocol1 } from './protocol1';
import { UserCredential } from './userCredential';


export interface StorageConfig { 
    protocol?: Protocol1;
    /**
     * The path on the remote system to use as the home directory for all API requests. For cases where the home directory should be dynamically defined, the ${USERNAME} token can be included in the homeDir value to represent the username of the authenticated user. ex. /home/${USERNAME}.
     */
    homeDir?: string;
    /**
     * The name of the zone when defining an IRODS system.
     */
    zone?: string;
    /**
     * The path on the remote system to use as the root for all API requests.
     */
    rootDir?: string;
    auth?: UserCredential;
    /**
     * The hostname or ip address of the storage server
     */
    host?: string;
    /**
     * The path on the remote system where apps will be stored if this is set as the default public storage system.
     */
    publicAppsDir?: string;
    /**
     * Whether the permissions set on the server should be pushed to the storage system itself. This only applies to IRODS and AWS systems.
     */
    mirror?: boolean;
    /**
     * The name of the target resource when defining an IRODS system.
     */
    resource?: string;
    /**
     * The port number of the storage server.
     */
    port?: number;
}
export namespace StorageConfig {
}


