/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Status } from './status';
import { Type } from './type';


export interface SystemSummary { 
    status?: Status;
    /**
     * Verbose description of this system.
     */
    description?: string;
    /**
     * Is the system the default for the authenticated user?
     */
    _default?: boolean;
    /**
     * Unique identifier for this system.
     */
    id?: string;
    type?: Type;
    /**
     * Is the system publicly available?
     */
    _public?: boolean;
    /**
     * Common name for this system.
     */
    name?: string;
}
export namespace SystemSummary {
}


