/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.1
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The authentication type.
 */
export type Type1 = 'LOCAL' | 'PAM' | 'PASSWORD' | 'SSHKEYS' | 'TOKEN' | 'X509';

export const Type1 = {
    Local: 'LOCAL' as Type1,
    Pam: 'PAM' as Type1,
    Password: 'PASSWORD' as Type1,
    Sshkeys: 'SSHKEYS' as Type1,
    Token: 'TOKEN' as Type1,
    X509: 'X509' as Type1
};

