/**
 * Tapis API
 * <h2> Your Science-as-a-Service API Platform. </h2> <p> For more information, visit <a href=\"https://tacc-cloud.readthedocs.io/projects/agave/en/latest/\">https://tacc-cloud.readthedocs.io/projects/agave/en/latest/</a> </p>
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: aci@tacc.utexas.edu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Protocol } from './protocol';


export interface UserCredentialServer { 
    /**
     * The hostname or ip address of the remote server.
     */
    endpoint?: string;
    protocol?: Protocol;
    /**
     * The port number of the remote server..
     */
    port?: object;
}
export namespace UserCredentialServer {
}


